name = "cfin7"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "46.32.178.51:443"
UUID = "9b505044-2a6a-4c9f-ac65-bd1d22be7d7d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
